# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/cognitivesearch/ci.mgmt.yml
    - sdk/cognitivesearch/Azure.ResourceManager.Cognitivesearch/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: cognitivesearch
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Cognitivesearch
      safeName: AzureResourceManagerCognitivesearch
