# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger: none

pr:
  branches:
    include:
    - main
    - feature/*
    - hotfix/*
    - release/*
  paths:
    include:
    - sdk/releaseplannertest/ci.mgmt.yml
    - sdk/releaseplannertest/Azure.ResourceManager.Releaseplannertest/

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: releaseplannertest
    LimitForPullRequest: true
    Artifacts:
    - name: Azure.ResourceManager.Releaseplannertest
      safeName: AzureResourceManagerReleaseplannertest
